SELECT o.ANIMAL_ID, o.ANIMAL_TYPE, o.NAME 
FROM ANIMAL_INS i
INNER JOIN ANIMAL_OUTS o ON i.ANIMAL_ID = o.ANIMAL_ID
WHERE 
    SEX_UPON_INTAKE LIKE 'Int%' 
    AND (
        SEX_UPON_OUTCOME LIKE 'Spa%'
        OR SEX_UPON_OUTCOME LIKE 'Neu%'
    )
ORDER BY o.ANIMAL_ID;