SELECT MCDP_CD AS 진료과코드, COUNT(*) AS 5월예약건수 
FROM APPOINTMENT
WHERE DATE_FORMAT(APNT_YMD, '%Y%m') = '202205' 
# AND APNT_CNCL_YN = 'N'
GROUP BY 진료과코드
ORDER BY 5월예약건수 ASC, 진료과코드 ASC;

# SELECT DATE_FORMAT(APNT_YMD, '%Y%m') FROM APPOINTMENT

# SELECT * FROM APPOINTMENT
# ORDER BY APNT_YMD ASC